apiVersion: v1
data:
  jiralert.yml: |
    defaults:
      {{ with .Values.jiralert.config }}
      # API access fields.
      user: 'JIRA_USERNAME'
      password: 'JIRA_PASSWORD'    
      api_url: {{ .api_url | quote }}

      # The type of JIRA issue to create. Required.
      issue_type: {{ .issue_type | quote }}

      # Issue priority. Optional.
        {{- if .issue_priority }}
      priority: {{ .issue_priority | quote }}
        {{- end }}

      # Go template invocation for generating the summary. Required.
      summary: {{`'{{ template "jira.summary" . }}'`}}

      # Go template invocation for generating the description. Required.
      description: {{`'{{ template "jira.description" . }}'`}}

      # State to transition into when reopening a closed issue. Required.
      reopen_state: {{ .reopen_state | quote }}

      # Do not reopen issues with this resolution. Optional. 
        {{- if .resolution }}
      wont_fix_resolution: {{ .resolution | quote }}
        {{- end }}

      # Amount of time after being closed that an issue should be reopened, after which, a new issue is created.
        {{- if .reopen_duration }}
      reopen_duration: {{ .reopen_duration | quote }}
        {{- end }}
      {{ end }}
    # Receiver definitions. At least one must be defined.
    receivers:
      {{- range .Values.jiralert.receivers }}
      - {{ . | toYaml | nindent 8 | trim }}
      {{ end }}
    # File containing template definitions. Required.
    template: jiralert.tmpl
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name"  . }}-config
  namespace: {{ include "resource.default.namespace"  . }}
