{{- with .Values.jiralert.credentials -}}
{{- if and .jira_username .jira_password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name"  $ }}-credentials
  namespace: {{ include "resource.default.namespace"  $ }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
type: Opaque
data:
  jira_username: {{ .jira_username | b64enc | quote }}
  jira_password: {{ .jira_password | b64enc | quote }}
{{- end -}}
{{- end -}}
