{{- if and .Values.secrets.jira_username .Values.secrets.jira_password  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name"  . }}-credentials
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  jira_username: {{ .Values.secrets.jira_username | b64enc | quote }}
  jira_password: {{ .Values.secrets.jira_password | b64enc | quote }}
{{- end -}}
