name: jiralert
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: docker.io
  name: giantswarm/jiralert
  tag: 1.2-extra-functions
  pullPolicy: IfNotPresent

init:
  registry: docker.io
  name: giantswarm/busybox
  tag: 1.34.1

pod:
  user:
    id: 1000
  group:
    id: 1000

psp:
  enabled: true

networkPolicy:
  enabled: true

nodeSelector: {}

# container resources
resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 100m
    memory: 220Mi

# container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true

jiralert:
  config:
    api_url: "https://example.atlassian.net/"
    issue_type: "Task"
    reopen_state: "To Do"
    resolution: "Won't Fix"
  receivers:
    # Receiver name must match the Alertmanager receiver name. Required.
    - name: 'jira-ab'
      # JIRA project to create the issue in. Required.
      project: AB
      # Copy all Prometheus labels into separate JIRA labels. Optional (default: false).
      add_group_labels: false

    - name: 'jira-xy'
      project: XY
      # Issue type. Overrides default. Optional.
      issue_type: Task
      # Standard or custom field values to set on created issue. Optional.
      # See https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#setting-custom-field-data-for-other-field-types for further examples.
      fields:
        # TextField
        customfield_10001: "Random text"
        # SelectList
        customfield_10002: '{"value": "red"}'
        # MultiSelect
        customfield_10003: '[{"value": "red"}, {"value": "blue"}, {"value": "green"}]'
